### ISSUE TITLE
No rule to make target 'build'.

### ISSUE THREAD

**Issue by maxi07** [rej696/elf2uf2#1]
Hey there, how do I actually build the application? Using your example results in an error.
```
Run git clone https://github.com/rej696/elf2uf2.git
Cloning into 'elf2uf2'...
make: *** No rule to make target 'build'.  Stop.
Error: Process completed with exit code 2.
```

**Comment by rej696** [comment]
Hi, sorry my readme is probably slightly unclear. You need to be in the directory of the repository to build the application. So you need to do `cd elf2uf2` before `make build`

![Screenshot_20230726_102723_com.termux~2.jpg](https://github.com/rej696/elf2uf2/assets/55083730/4f54f682-5b6f-436f-b0b4-cc5784d6b615)

If you still have issues let me know :)
