### ISSUE TITLE
[Question] Does it support the Windows MSVC++ compiler?

### ISSUE THREAD

**Issue by matkuki** [rej696/elf2uf2#2]
Hi,

I tried compiling it with the Windows MSVC++ compiler, and it compiles successfully, but the resulting `elf2uf2.exe` does not work correctly. It produces a `.uf2` file, but it is invalid, for example: it converts a 148kB `.elf` file into a 3kB `.uf2` file.
Is this compiler even supported officially?

Thanks

**Comment by rej696** [comment]
I have only compiled this using g++ on Linux, I had a quick look through the Pico SDK documentation, but couldn't find anything about that compiler. This repo is just a couple of files extracted from the Pico SDK, so if it works for the Pico SDK, it should work here. But I'm not very familiar with compiling things on windows sorry. If you are able to use windows subsystem for linux or cygwin with the g++ compiler, then it should work fine.

I hope you manage to figure it out :)

**Comment by matkuki** [comment]
> If you are able to use windows subsystem for linux or cygwin with the g++ compiler, then it should work fine.

Thanks for the suggestion, will try it and report back 👍
